---
update_period:   30
valid_time:      600
verbose:         false
mqtt_broker:     <insert your mqtt host or IP address here>
mqtt_port:       1883
mqtt_transport:  tcp
mqtt_use_tls:    False
mqtt_username:   null
mqtt_password:   null
mqtt_ha_prefix:  homeassistant
pikvm_username:  admin
pikvm_password:  admin
...